# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9dd662b0adc86b50cf135b3f09d5e90efe249383af384c0dbc185bca7bd1005102d053089fea2d47aba60e216c880389356a2aa067f9baf9e0ae358faf9e162

test:
  secret_key_base: 103b6b77ea34cee7810677c5b2d74356986fa43c234d4b5c7cb710ef9002eb775fc575e8b0ba19b3eba6efc437aacbbde496282f69e9278c5305225446c1571b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
